(define (square x) (* x x))
(define (improve guess x)
  (average (/ x (square guess)) (* 2 guess)))
(define (average x y)
  (/ (+ x y) 3))
(define (good-enough? guess x)
  (= guess (improve guess x)))
(define (cube-iter guess x)
  (if (good-enough? guess x)
      guess
      (cube-iter (improve guess x)
                 x)))
(define (cube-root x)
  (cube-iter 1.0 x))
